version: '3.8'

services:
  redis:
      image: redis:latest
      container_name: redis-server
      restart: always
      ports:
        - "6379:6379"
      volumes:
        - redis-data:/data
      command: ["redis-server", "--appendonly", "yes"] 
  
  postgres:
      image: postgres:15
      container_name: postgres-db
      restart: always
      environment:
        POSTGRES_DB: myapp
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password123
      volumes:
        - postgres_data:/var/lib/postgresql/data
        - ./init-scripts:/docker-entrypoint-initdb.d
      ports:
        - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-gui
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "8080:80"
    depends_on:
      - postgres
volumes:
  redis-data:
  postgres_data:
  pgadmin_data:
